name: Terraform on GCP
on:
    workflow_dispatch: 
        inputs:
            WORKING_DIR:
                description: "Enter the working dir to create the resources on GCP"
                type: string
            TERRAFORM_COMMAND:
                description: "Choose terraform apply or destroy command"
                default: "apply"
                type: choice
                options:
                  - apply
                  - destroy       
                
jobs:
    terraform-on-gcp:
        permissions: write-all
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ${{ inputs.WORKING_DIR }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.GKE_SA }}'
            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v2'
              with:
                version: '>= 363.0.0'
            - name: Check the Gcloud Version
              run: gcloud --version
                
            - name: Terraform setup
              uses: hashicorp/setup-terraform@v3

            - name: Terraform init
              run: terraform init

            - name: Terraform fmt
              run: terraform fmt

            - name: Terraform validate
              run: terraform validate
             

            - name: Terraform plan
              run: terraform plan
              

            - name: Terraform ${{ inputs.TERRAFORM_COMMAND }}
              run: terraform ${{ inputs.TERRAFORM_COMMAND }} -auto-approve
              
